export const anketa = {
  accountNumber: 'string',
  additionalMonthlyIncomeAmount: 0,
  additionalPhone: 'string',
  agreementFormLink: '/string',
  approvedInterestRate: 0,
  approvedLoanAmount: 0,
  approvedLoanTermMonths: 0,
  approvedMonthlyPayment: 0,
  bankIdCode: 'string',
  batchDocumentLink: 'string',
  birthDate: '2020-11-27',
  campaignParticipant: true,
  dboActivated: false,
  email: 'string',
  firstName: 'string',
  jobLossProtection: true,
  lastName: 'string',
  lastWorkExperienceMonths: 0,
  lifeAndHealthProtection: true,
  mainMonthlyIncomeAmount: 0,
  middleName: 'string',
  mobilePhone: 'string',
  passportIssueAuthorityCode: 'string',
  passportIssueAuthorityName: 'string',
  passportIssueDate: '2020-11-27',
  passportNumber: 'string',
  passportSeries: 'string',
  registrationAddress: 'Финляндия, Хельсинки, улица Мира, 107',
  requestedLoanAmount: 0,
  requestedLoanTermMonths: 0,
  smsInforming: true,
  status: 'REGISTRATION_ADDRESS',
  workIndustry: 'string',
  workInn: 'string',
  workPlace: 'string',
};

export const getAnketa = (changes: Partial<typeof anketa>) => {
  const updatedAnketa = {...anketa, ...changes};
  return updatedAnketa;
}
