export const fallbackAgreementLink = 'https://cash.otpbank.ru/public/bki_soglasie.docx';

export const workIndustryList = [
  {id: 'RGB_INDUSTRY_9', title: 'Ресторанный бизнес/Общественное питание'},
  {id: 'RGB_INDUSTRY_3', title: 'Нефтегазовая промышленность'},
  {id: 'RGB_INDUSTRY_3$1', title: 'Энергетика'},
  {id: 'RGB_INDUSTRY_7', title: 'Коммунальное хоз-во/Дорожные службы'},
  {id: 'RGB_INDUSTRY_18', title: 'Страхование'},
  {id: 'RGB_INDUSTRY_18$1', title: 'Банк/Финансы'},
  {id: 'RGB_INDUSTRY_18$2', title: 'Управляющая компания'},
  {id: 'RGB_INDUSTRY_4', title: 'Здравоохранение'},
  {id: 'RGB_INDUSTRY_12', title: 'Салоны красоты и здоровья'},
  {id: 'RGB_INDUSTRY_13', title: 'Сборочные производства'},
  {id: 'RGB_INDUSTRY_14', title: 'Сельское хозяйство'},
  {id: 'RGB_INDUSTRY_19', title: 'Химия/Парфюмерия/Фармацевтика'},
  {id: 'RGB_INDUSTRY_6', title: 'Туризм'},
  {id: 'RGB_INDUSTRY_6$1', title: 'Развлечения/Искусство'},
  {id: 'RGB_INDUSTRY_21', title: 'Юридические услуги/нотариальные услуги'},
  {id: 'RGB_INDUSTRY_16', title: 'Недвижимость'},
  {id: 'RGB_INDUSTRY_16$1', title: 'Торговля'},
  {id: 'RGB_INDUSTRY_8', title: 'Образование'},
  {id: 'RGB_INDUSTRY_8$1', title: 'Наука'},
  {id: 'RGB_INDUSTRY_20', title: 'ЧОП/Детективная д-ть'},
  {id: 'RGB_INDUSTRY_5', title: 'Информационные технологии'},
  {id: 'RGB_INDUSTRY_5$1', title: 'Информационные услуги'},
  {id: 'RGB_INDUSTRY_17', title: 'Транспорт'},
  {id: 'RGB_INDUSTRY_17$1', title: 'Логистика'},
  {id: 'RGB_INDUSTRY_2', title: 'Государственная служба'},
  {id: 'RGB_INDUSTRY_11', title: 'Маркетинг'},
  {id: 'RGB_INDUSTRY_11$1', title: 'Подбор персонала'},
  {id: 'RGB_INDUSTRY_11$2', title: 'СМИ/Реклама/PR-агенства'},
  {id: 'RGB_INDUSTRY_10', title: 'Металлургия/Промышленность/Машиностроение'},
  {id: 'RGB_INDUSTRY_15', title: 'Строительство'},
  {id: 'OTHER', title: 'Другие сферы'},
];
