import {TAnketaStep} from 'context/Anketa'

export const anketaRoutesMap = new Map<TAnketaStep, {url: string; step: number}>([
  ['LOAN_PARAMS', {url: '/anketa/calculator', step: 1}],
  ['PASSPORT', {url: '/anketa/passport', step: 2}],
  ['PASSPORT_PHOTO', {url: '/anketa/photo', step: 2}],
  ['REGISTRATION_ADDRESS', {url: '/anketa/registration', step: 2}],
  ['CHANGED_REGISTRATION_ADDRESS', {url: '/anketa/regchanged', step: 2}],
  ['DETAILS', {url: '/anketa/details', step: 2}],
  ['AGREEMENT_SMS_CODE', {url: '/anketa/agreementsms', step: 3}],
  ['PENDING_ADVANCE_SCORING', {url: '/anketa/pendingadvancescoring', step: 3}],
  ['ADVANCE_SCORING_REFUSAL', {url: '/anketa/scoringrefus', step: 3}],
  ['TRANSFER_DETAILS', {url: '/anketa/transfer', step: 3}],
  ['PENDING_SCORING', {url: '/anketa/pendingscoring', step: 3}],
  ['SCORING', {url: '/anketa/pendingscoring', step: 3}],
  ['APPROVED', {url: '/anketa/approved', step: 4}],
  ['REJECTED', {url: '/anketa/rejected', step: 4}],
  ['SIGNATURE_SMS_CODE', {url: '/anketa/signaturesms', step: 4}],
  ['PENDING_DOCUMENTS', {url: '/anketa/pendingdocuments', step: 4}],
  ['EXECUTION', {url: '/anketa/execution', step: 4}],
  ['EXECUTION_FAILED', {url: '/anketa/execfail', step: 5}],
  ['COMPLETED', {url: '/anketa/completed', step: 5}],
])

export const routeMap = {
  LOAN_PARAMS: '/anketa/calculator',
  PASSPORT: '/anketa/passport',
  PASSPORT_PHOTO: '/anketa/photo',
  REGISTRATION_ADDRESS: '/anketa/registration',
  CHANGED_REGISTRATION_ADDRESS: '/anketa/regchanged',
  DETAILS: '/anketa/details',
  AGREEMENT_SMS_CODE: '/anketa/agreementsms',
  PENDING_ADVANCE_SCORING: '/anketa/pendingadvancescoring',
  ADVANCE_SCORING_REFUSAL: '/anketa/scoringrefus',
  TRANSFER_DETAILS: '/anketa/transfer',
  PENDING_SCORING: '/anketa/pendingscoring',
  SCORING: '/anketa/pendingscoring',
  APPROVED: '/anketa/approved',
  REJECTED: '/anketa/rejected',
  SIGNATURE_SMS_CODE: '/anketa/signaturesms',
  PENDING_DOCUMENTS: '/anketa/pendingdocuments',
  EXECUTION: '/anketa/execution',
  EXECUTION_FAILED: '/anketa/execfail',
  COMPLETED: '/anketa/completed',
}
